name = "VimBindings"
uuid = "51b3953f-5e5d-4a6b-bd62-c64b6fa1518a"
authors = ["Caleb Allen <mail@caleb.dev> and contributors"]
version = "0.3.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
REPL = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
DataStructures = "0.18.13"
Match = "~1.2.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
